<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <Target Name="_RemovePublishDirBeforePublishing" BeforeTargets="BeforePublish">
        <RemoveDir Directories="$(PublishDir)" Condition="'$(PublishDir)' != ''" />
    </Target>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
      <PackageReference Include="DotNetEnv" Version="3.2.0" />
      <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    </ItemGroup>
    
    <ItemGroup>
      <None Include="wwwroot\fonts.css" />
    </ItemGroup>

    <ItemGroup>
        <!-- Ensure .razor.js files are treated as static assets -->
        <None Update="Components\Layout\MainLayout.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Components\Elements\ThemeToggle.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Components\Elements\NavMenu.razor.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Layout\MainLayout.razor" />
      <_ContentIncludedByDefault Remove="Components\Layout\SiteHeader.razor" />
      <_ContentIncludedByDefault Remove="Components\Elements\Layout\MainLayout.razor" />
      <_ContentIncludedByDefault Remove="Components\Elements\Layout\SiteHeader.razor" />
    </ItemGroup>
    
    <!-- Exclude private data files from the build output -->
    <ItemGroup>
        <Content Remove="data.json" />
        <Content Remove="cache\**" />
    </ItemGroup>

</Project>
